export * from './Author.types';
export * from './Book.types';
export * from './Conference.types';
export * from './Record.types';
export * from './SocialMedia.types';
export * from './CarouselImage.types';
export * from './Links.types';
export * from './CV.types';
export * from './CongressArticle.types';