export * from './NavBar';
export * from './SocialMedia';
export * from './Header';
export * from './Section';
export * from './MiniArticle';
export * from './Article';
export * from './InfoSection';
export * from './ItemList';
export * from './CardPeople';